// ============================================================
//  CHIBO.JS - DANH SÁCH TỔ CHỨC ĐẢNG
//  Nguồn: Danh mục TC CS Đảng - Đảng viên, 16/5/2026
//  Đảng ủy phường Thanh Khê
// ============================================================

const DS_NHOM = [
  {
    id: "nhom1",
    ten: "I. ĐẢNG BỘ CƠ SỞ",
    danhSach: [
      "Đảng ủy các cơ quan Đảng",
      "Đảng ủy UBND phường",
      "Đảng ủy Công an phường",
      "Đảng bộ Trung tâm Y tế khu vực Thanh Khê",
      "Đảng bộ Trường Thể dục Thể Thao Đà Nẵng",
      "Đảng bộ Trường Cao đẳng Thương Mại",
      "Đảng bộ Công ty Cổ phần xây dựng công trình 512",
      "Đảng bộ Công ty Cổ phần Dược DANAPHA",
      "Đảng bộ Công ty Cổ phần Dệt May 29/3",
      "Đảng bộ Công ty Cổ phần In và Dịch vụ Đà Nẵng",
      "Đảng bộ Bưu điện thành phố Đà Nẵng",
      "Đảng bộ Công ty TNHH MTV Thương Mại Quảng Nam - Đà Nẵng",
      "Đảng bộ Ngân hàng TMCP Công Thương Việt Nam - Chi nhánh Đà Nẵng"
    ]
  },
  {
    id: "nhom2",
    ten: "II. CHI BỘ CƠ SỞ",
    danhSach: [
      "Chi bộ Trường THPT Thanh Khê",
      "Chi bộ Trường THPT Thái Phiên",
      "Chi bộ Trung tâm Giáo dục thường xuyên số 2",
      "Chi bộ Trung tâm Huấn luyện Vận động viên trẻ Quốc gia Đà Nẵng",
      "Chi bộ Trường THPT Quang Trung (tư thục)",
      "Chi bộ Cty Cổ phần Xây lắp Điện và Cơ khí mạ Đà Nẵng",
      "Chi bộ Cty Cổ phần Dịch vụ bảo vệ An Ninh",
      "Chi bộ Cty CP Tư vấn và Phát triển kỹ thuật Tài nguyên nước",
      "Chi bộ Cty Cổ phần Túi xách Đà Nẵng",
      "Chi bộ Cty TNHH Dịch vụ Bảo vệ an ninh Quốc Đô",
      "Chi bộ Cty Cổ phần Tư vấn xây dựng và Đầu tư Trường Định",
      "Chi bộ Ngân hàng TMCP An Bình Chi nhánh Đà Nẵng",
      "Chi bộ Cty Bảo hiểm PJICO Đà Nẵng",
      "Chi bộ Ngân hàng TMCP Tiên Phong Chi nhánh Đà Nẵng",
      "Chi bộ VPĐD Miền Trung Ngân Hàng TMCP Kỹ Thương VN",
      "Chi bộ Cty Bảo Minh Đà Nẵng",
      "Chi bộ quân sự phường",
      "Chi bộ Trạm Y tế",
      "Chi bộ Trường Mầm non Cẩm Tú",
      "Chi bộ Trường Mầm non Tuổi Hoa",
      "Chi bộ Trường Mầm non Mẫu Đơn",
      "Chi bộ Trường Mầm non Phong Lan",
      "Chi bộ Trường Mầm non Hải Đường",
      "Chi bộ Trường Mầm non Thủy Tiên",
      "Chi bộ Trường Mầm non Cẩm Nhung",
      "Chi bộ Trường Mầm non Hoàng Mai",
      "Chi bộ Trường Mầm non Tường Vy",
      "Chi bộ Trường Tiểu học Đoàn Thị Điểm",
      "Chi bộ Trường Tiểu học Lê Quang Sung",
      "Chi bộ Trường Tiểu học Huỳnh Ngọc Huệ",
      "Chi bộ Trường Tiểu học Lê Văn Tám",
      "Chi bộ Trường Tiểu học Dũng Sĩ Thanh Khê",
      "Chi bộ Trường Tiểu học Nguyễn Đức Cảnh",
      "Chi bộ Trường Tiểu học Hà Huy Tập",
      "Chi bộ Trường Tiểu học Nguyễn Trung Trực",
      "Chi bộ Trường Tiểu học Đinh Bộ Lĩnh",
      "Chi bộ Trường Tiểu học Điện Biên Phủ",
      "Chi bộ Trường Tiểu học Trần Cao Vân",
      "Chi bộ Trường Tiểu học Nguyễn Bá Ngọc",
      "Chi bộ Trường Tiểu học Hàm Nghi",
      "Chi bộ Trường Tiểu học Hoa Lư",
      "Chi bộ Trường THCS Phan Đình Phùng",
      "Chi bộ Trường THCS Huỳnh Thúc Kháng",
      "Chi bộ Trường THCS Đỗ Đăng Tuyển",
      "Chi bộ Trường THCS Nguyễn Chơn",
      "Chi bộ Trường THCS Hoàng Diệu",
      "Chi bộ Trường THCS Lê Thị Hồng Gấm",
      "Chi bộ Trường THCS Nguyễn Duy Hiệu",
      "Chi bộ Trường THCS Nguyễn Trãi",
      "Chi bộ Trường THCS Chu Văn An",
      "Chi bộ Trường THCS Nguyễn Thị Minh Khai",
      "Chi bộ BIDV Văn phòng đại diện tại TP Đà Nẵng"
    ]
  },
  {
    id: "nhom3",
    ten: "III. CHI BỘ TRỰC THUỘC",
    danhSach: [
      "Chi bộ Xuân Hòa 1",
      "Chi bộ Xuân Hòa 2",
      "Chi bộ Xuân Hòa A1",
      "Chi bộ Thanh Xuân",
      "Chi bộ Thanh Phong 2",
      "Chi bộ Thanh Phong 3",
      "Chi bộ Thanh Huy 1",
      "Chi bộ Thanh Huy 2",
      "Chi bộ Thanh Tân 1",
      "Chi bộ Thanh Tân 2",
      "Chi bộ Thanh Minh 1",
      "Chi bộ Thanh Minh 2",
      "Chi bộ Thanh Hòa",
      "Chi bộ Thanh Minh",
      "Chi bộ Thanh Hà",
      "Chi bộ Thanh Thủy",
      "Chi bộ 1 Phần Lăng",
      "Chi bộ 2 Phần Lăng",
      "Chi bộ 3 Phần Lăng",
      "Chi bộ 4 Phần Lăng",
      "Chi bộ 5 Phần Lăng",
      "Chi bộ Khu dân cư 372",
      "Chi bộ 1 Thanh Khê",
      "Chi bộ 2 Thanh Khê",
      "Chi bộ 3 Thanh Khê",
      "Chi bộ 4 Thanh Khê",
      "Chi bộ 1 Xuân Hòa",
      "Chi bộ 2 Xuân Hòa",
      "Chi bộ 3 Xuân Hòa",
      "Chi bộ 4 Xuân Hòa",
      "Chi bộ 5 Xuân Hòa",
      "Chi bộ 1 Xuân Hòa A",
      "Chi bộ 2 Xuân Hòa A",
      "Chi bộ 3 Xuân Hòa A",
      "Chi bộ 4 Xuân Hòa A",
      "Chi bộ 5 Xuân Hòa A",
      "Chi bộ 6 Xuân Hòa A",
      "Chi bộ 7 Xuân Hòa A",
      "Chi bộ Thanh Khê Tây 1",
      "Chi bộ Thanh Khê Tây 2",
      "Chi bộ Thanh Khê Tây 4A",
      "Chi bộ Thanh Khê Tây 4B",
      "Chi bộ Thanh Khê Tây 5",
      "Chi bộ Thanh Khê Tây 6",
      "Chi bộ Thanh Khê Tây 7",
      "Chi bộ Thanh Khê Tây 8",
      "Chi bộ Thanh Khê Tây 9",
      "Chi bộ Thanh Khê Tây 10",
      "Chi bộ Thanh Khê Tây 11",
      "Chi bộ Thanh Khê Tây 12",
      "Chi bộ Thanh Khê Tây 13",
      "Chi bộ Thanh Khê Tây 14",
      "Chi bộ Thanh Khê Tây 15",
      "Chi bộ Thanh Khê Tây 16",
      "Chi bộ Thanh Khê Tây 17",
      "Chi bộ Trung Nghĩa 2",
      "Chi bộ Trung Nghĩa 5",
      "Chi bộ Hòa Phú 4",
      "Chi bộ Hòa Phú 4A",
      "Chi bộ Hòa Phú 5",
      "Chi bộ Hòa Phú 5A",
      "Chi bộ Hòa Phú 5B",
      "Chi bộ Tam Thuận 1",
      "Chi bộ Tam Thuận 2",
      "Chi bộ Tam Thuận 3",
      "Chi bộ Tam Thuận 4",
      "Chi bộ Tam Thuận 5",
      "Chi bộ Tam Thuận 6",
      "Chi bộ Tam Thuận 7",
      "Chi bộ Tam Thuận 8",
      "Chi bộ Tam Thuận 9",
      "Chi bộ Tam Thuận 10",
      "Chi bộ Tam Thuận 11",
      "Chi bộ Tam Thuận 12",
      "Chi bộ Tam Thuận 13",
      "Chi bộ Tam Thuận 14",
      "Chi bộ Tam Thuận 15",
      "Chi bộ Tam Thuận 16",
      "Chi bộ Tam Thuận 17",
      "Chi bộ Tân Trung 1",
      "Chi bộ Tân Trung 2",
      "Chi bộ Hà Đông 1",
      "Chi bộ Hà Đông 2",
      "Chi bộ Hà Đông 3",
      "Chi bộ Xuân Đán 1",
      "Chi bộ Xuân Đán 2",
      "Chi bộ Xuân Đán 3",
      "Chi bộ Xuân Đán 4",
      "Chi bộ Xuân Đán 5",
      "Chi bộ Xuân Đán 6",
      "Chi bộ Thuận An 1",
      "Chi bộ Thuận An 2",
      "Chi bộ Thuận An 3",
      "Chi bộ Thuận An 4",
      "Chi bộ Thuận An 5",
      "Chi bộ Thuận An 6",
      "Chi bộ Tân Chánh 1",
      "Chi bộ Tân Chánh 2",
      "Chi bộ Tân Chánh 3",
      "Chi bộ 1 Chính Trạch",
      "Chi bộ 2 Chính Trạch",
      "Chi bộ 1 Tân Ninh A",
      "Chi bộ 2 Tân Ninh A",
      "Chi bộ 3 Tân Ninh A",
      "Chi bộ 4 Tân Ninh A",
      "Chi bộ 1 Tân Ninh B",
      "Chi bộ 2 Tân Ninh B",
      "Chi bộ 3 Tân Ninh B",
      "Chi bộ 1 Tân An B",
      "Chi bộ 2 Tân An B",
      "Chi bộ 3 Tân An B",
      "Chi bộ 4 Tân An B",
      "Chi bộ 5 Tân An B",
      "Chi bộ 6 Tân An B",
      "Chi bộ 7 Tân An B",
      "Chi bộ 8 Tân An B",
      "Chi bộ Tân An A1",
      "Chi bộ Tân An A2",
      "Chi bộ Tân An A3",
      "Chi bộ Tân An A4",
      "Chi bộ Tân Sinh A1",
      "Chi bộ Tân Sinh A2",
      "Chi bộ Tân Sinh B1",
      "Chi bộ Tân Sinh B2",
      "Chi bộ Tân Sinh B3",
      "Chi bộ Núi Cùng 1",
      "Chi bộ Núi Cùng 2",
      "Chi bộ Núi Cùng 3",
      "Chi bộ Xuân Hòa B1",
      "Chi bộ Xuân Hòa B2",
      "Chi bộ Xuân Hòa B3",
      "Chi bộ Xuân Hòa B4",
      "Chi bộ Bàu Sen 1",
      "Chi bộ Bàu Sen 2",
      "Chi bộ Bàu Sen 3",
      "Chi bộ Tam Giác 1",
      "Chi bộ Tam Giác 2",
      "Chi bộ Tam Giác 3A",
      "Chi bộ Tam Giác 3B",
      "Chi bộ Trung Bình A1",
      "Chi bộ Trung Bình A2",
      "Chi bộ Trung Bình A3",
      "Chi bộ Trung Bình B1",
      "Chi bộ Trung Bình B2",
      "Chi bộ Trung Lập A1",
      "Chi bộ Trung Lập A2",
      "Chi bộ Trung Lập A3",
      "Chi bộ Trung Lập A4",
      "Chi bộ Trung Lập B1",
      "Chi bộ Trung Lập B2",
      "Chi bộ Trung Lập B3",
      "Chi bộ Trung Lập B4",
      "Chi bộ Trung Lập B5",
      "Chi bộ Trung Lập B6",
      "Chi bộ Trung Lập B7",
      "Chi bộ Vĩnh An A1",
      "Chi bộ Vĩnh An A2",
      "Chi bộ Vĩnh An B1",
      "Chi bộ Vĩnh An B2",
      "Chi bộ Vĩnh An B3",
      "Chi bộ Trung Hòa A1",
      "Chi bộ Trung Hòa A2",
      "Chi bộ Trung Hòa A3",
      "Chi bộ Trung Hòa B1",
      "Chi bộ Trung Hòa B2",
      "Chi bộ Trung Hòa B3",
      "Chi bộ Tân Lập A1",
      "Chi bộ Tân Lập A2",
      "Chi bộ Tân Lập A3",
      "Chi bộ Tân Lập B1",
      "Chi bộ Tân Lập B2",
      "Chi bộ Tân Lập B3",
      "Chi bộ Tân Lập B4",
      "Chi bộ Tân Lập B5"
    ]
  },
  {
    id: "nhom4",
    ten: "IV. CHI BỘ DOANH NGHIỆP",
    danhSach: [
      "Chi bộ Công ty Cổ phần Xây dựng Giao thông 503",
      "Chi bộ Trường Trung cấp Chuyên nghiệp Ý Việt",
      "Chi bộ Công ty Cổ phần Sinh học Minh Hồng",
      "Chi bộ Tổng Công ty Miền Trung - CTCP",
      "Chi bộ Công ty TNHH Kiểm toán & Dịch vụ tin học Moore Aisc tại Đà Nẵng",
      "Chi bộ Công ty Cổ phần Giám định Á Việt"
    ]
  }
];

// Danh sách phẳng toàn bộ (dùng cho code.gs)
const DS_CHI_BO = DS_NHOM.flatMap(nhom => nhom.danhSach);

// Danh sách phẳng kèm nhóm (dùng cho giao diện dropdown nhóm)
const DS_CHI_BO_FULL = DS_NHOM.flatMap(nhom =>
  nhom.danhSach.map(ten => ({ nhom: nhom.ten, ten }))
);
